include_recipe "sprout-osx-base::bash_it"
include_recipe "pivotal_workstation::github_for_mac"
include_recipe "sprout-osx-base::homebrew"
include_recipe "pivotal_workstation::iterm2"
include_recipe "sprout-osx-apps::virtualbox"
include_recipe "sprout-osx-apps::caffeine"
include_recipe "sprout-osx-apps::skype"
include_recipe "sprout-osx-apps::vlc"
include_recipe "sprout-osx-apps::hipchat"

