include_recipe "pivotal_workstation::flycut"
include_recipe "sprout-osx-settings::function_keys"
include_recipe "pivotal_workstation::github_ssh_keys"
include_recipe "pivotal_workstation::keyboard_preferences"
include_recipe "pivotal_workstation::libreoffice"
include_recipe "pivotal_workstation::menubar_preferences"
include_recipe "pivotal_workstation::osx_updates"
include_recipe "pivotal_workstation::timemachine_preferences"
